{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "finishTime": 1782933782923,
     "inputWidgets": {},
     "nuid": "45cb4ff5-11cd-475e-a6d1-7822bf407a9f",
     "showTitle": false,
     "startTime": 1782933769641,
     "submitTime": 1782933733510,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating synthetic airline dataset...\nGenerated 500,000 flight records\nShape: (500000, 17)\nDate range: 2023-01-01 to 2023-12-31\nAvg ticket price: $634.05\nAvg load factor: 76.5%\n"
     ]
    },
    {
     "output_type": "execute_result",
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>FL_DATE</th>\n",
       "      <th>MONTH</th>\n",
       "      <th>DAY_OF_WEEK</th>\n",
       "      <th>IS_WEEKEND</th>\n",
       "      <th>AIRLINE</th>\n",
       "      <th>ORIGIN</th>\n",
       "      <th>DEST</th>\n",
       "      <th>ROUTE</th>\n",
       "      <th>DEP_HOUR</th>\n",
       "      <th>IS_PEAK_HOUR</th>\n",
       "      <th>DISTANCE</th>\n",
       "      <th>DEP_DELAY</th>\n",
       "      <th>SEATS_CAPACITY</th>\n",
       "      <th>SEATS_SOLD</th>\n",
       "      <th>LOAD_FACTOR</th>\n",
       "      <th>TICKET_PRICE</th>\n",
       "      <th>FLIGHT_REVENUE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2023-11-24</td>\n",
       "      <td>11</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>FZ</td>\n",
       "      <td>MCT</td>\n",
       "      <td>JFK</td>\n",
       "      <td>MCT-JFK</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>5625</td>\n",
       "      <td>-3.0</td>\n",
       "      <td>180</td>\n",
       "      <td>117</td>\n",
       "      <td>0.6544</td>\n",
       "      <td>742.26</td>\n",
       "      <td>86844.42</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2023-02-27</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>EY</td>\n",
       "      <td>DOH</td>\n",
       "      <td>CDG</td>\n",
       "      <td>DOH-CDG</td>\n",
       "      <td>22</td>\n",
       "      <td>0</td>\n",
       "      <td>1810</td>\n",
       "      <td>40.0</td>\n",
       "      <td>120</td>\n",
       "      <td>111</td>\n",
       "      <td>0.9288</td>\n",
       "      <td>371.13</td>\n",
       "      <td>41195.43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2023-01-13</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>EK</td>\n",
       "      <td>JFK</td>\n",
       "      <td>DXB</td>\n",
       "      <td>JFK-DXB</td>\n",
       "      <td>17</td>\n",
       "      <td>1</td>\n",
       "      <td>5219</td>\n",
       "      <td>92.0</td>\n",
       "      <td>180</td>\n",
       "      <td>164</td>\n",
       "      <td>0.9113</td>\n",
       "      <td>809.98</td>\n",
       "      <td>132836.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2023-05-21</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>WY</td>\n",
       "      <td>KWI</td>\n",
       "      <td>DOH</td>\n",
       "      <td>KWI-DOH</td>\n",
       "      <td>7</td>\n",
       "      <td>1</td>\n",
       "      <td>6355</td>\n",
       "      <td>11.0</td>\n",
       "      <td>150</td>\n",
       "      <td>103</td>\n",
       "      <td>0.6887</td>\n",
       "      <td>924.58</td>\n",
       "      <td>95231.74</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2023-05-06</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>1</td>\n",
       "      <td>EY</td>\n",
       "      <td>MCT</td>\n",
       "      <td>DXB</td>\n",
       "      <td>MCT-DXB</td>\n",
       "      <td>21</td>\n",
       "      <td>0</td>\n",
       "      <td>2822</td>\n",
       "      <td>-5.0</td>\n",
       "      <td>150</td>\n",
       "      <td>103</td>\n",
       "      <td>0.6908</td>\n",
       "      <td>434.72</td>\n",
       "      <td>44776.16</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      FL_DATE  MONTH  DAY_OF_WEEK  ...  LOAD_FACTOR TICKET_PRICE FLIGHT_REVENUE\n",
       "0  2023-11-24     11            4  ...       0.6544       742.26       86844.42\n",
       "1  2023-02-27      2            0  ...       0.9288       371.13       41195.43\n",
       "2  2023-01-13      1            4  ...       0.9113       809.98      132836.72\n",
       "3  2023-05-21      5            6  ...       0.6887       924.58       95231.74\n",
       "4  2023-05-06      5            5  ...       0.6908       434.72       44776.16\n",
       "\n",
       "[5 rows x 17 columns]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime, timedelta\n",
    "import random\n",
    "\n",
    "print(\"Generating synthetic airline dataset...\")\n",
    "\n",
    "np.random.seed(42)\n",
    "random.seed(42)\n",
    "\n",
    "AIRLINES = [\"EK\", \"EY\", \"FZ\", \"G9\", \"WY\"]\n",
    "AIRPORTS = [\"DXB\", \"AUH\", \"SHJ\", \"DOH\", \"KWI\", \"BAH\", \"MCT\", \"JFK\", \"LHR\", \"CDG\"]\n",
    "N_RECORDS = 500000\n",
    "\n",
    "start_date = datetime(2023, 1, 1)\n",
    "dates = [start_date + timedelta(days=random.randint(0, 364)) for _ in range(N_RECORDS)]\n",
    "\n",
    "origins = np.random.choice(AIRPORTS, N_RECORDS)\n",
    "dests = []\n",
    "for o in origins:\n",
    "    d = o\n",
    "    while d == o:\n",
    "        d = random.choice(AIRPORTS)\n",
    "    dests.append(d)\n",
    "\n",
    "# ✅ KEY FIX: normalize=True forces numpy to auto-correct any floating point issues\n",
    "raw_probs = np.array([1,1,1,1,2,3,6,7,7,6,5,4,4,4,4,4,5,7,7,6,5,4,3,2], dtype=float)\n",
    "probs = raw_probs / raw_probs.sum()  # Divides each value so total = exactly 1.0\n",
    "dep_hours = np.random.choice(range(24), N_RECORDS, p=probs)\n",
    "\n",
    "distances = np.random.randint(200, 8000, N_RECORDS)\n",
    "\n",
    "delays = np.where(\n",
    "    np.random.random(N_RECORDS) < 0.75,\n",
    "    np.random.randint(-10, 15, N_RECORDS),\n",
    "    np.random.randint(15, 180, N_RECORDS)\n",
    ").astype(float)\n",
    "\n",
    "capacity = np.random.choice([120, 150, 180, 220, 350], N_RECORDS)\n",
    "load_factor = np.random.uniform(0.55, 0.98, N_RECORDS)\n",
    "seats_sold = (capacity * load_factor).astype(int)\n",
    "\n",
    "months = [d.month for d in dates]\n",
    "is_peak_month = np.isin(months, [6, 7, 8, 12])\n",
    "is_peak_hour = ((dep_hours >= 7) & (dep_hours <= 9)) | ((dep_hours >= 17) & (dep_hours <= 19))\n",
    "is_weekend = np.array([d.weekday() >= 5 for d in dates])\n",
    "\n",
    "base_price = distances * 0.12 + 80\n",
    "price = base_price + is_peak_month * 60 + is_peak_hour * 45 + is_weekend * 30 + (load_factor > 0.85) * 50\n",
    "price = np.round(price + np.random.normal(0, 15, N_RECORDS), 2)\n",
    "revenue = np.round(seats_sold * price, 2)\n",
    "\n",
    "df = pd.DataFrame({\n",
    "    \"FL_DATE\": [d.strftime(\"%Y-%m-%d\") for d in dates],\n",
    "    \"MONTH\": months,\n",
    "    \"DAY_OF_WEEK\": [d.weekday() for d in dates],\n",
    "    \"IS_WEEKEND\": is_weekend.astype(int),\n",
    "    \"AIRLINE\": np.random.choice(AIRLINES, N_RECORDS),\n",
    "    \"ORIGIN\": origins,\n",
    "    \"DEST\": dests,\n",
    "    \"ROUTE\": [f\"{o}-{d}\" for o, d in zip(origins, dests)],\n",
    "    \"DEP_HOUR\": dep_hours,\n",
    "    \"IS_PEAK_HOUR\": is_peak_hour.astype(int),\n",
    "    \"DISTANCE\": distances,\n",
    "    \"DEP_DELAY\": delays,\n",
    "    \"SEATS_CAPACITY\": capacity,\n",
    "    \"SEATS_SOLD\": seats_sold,\n",
    "    \"LOAD_FACTOR\": np.round(load_factor, 4),\n",
    "    \"TICKET_PRICE\": price,\n",
    "    \"FLIGHT_REVENUE\": revenue\n",
    "})\n",
    "\n",
    "print(f\"Generated {len(df):,} flight records\")\n",
    "print(f\"Shape: {df.shape}\")\n",
    "print(f\"Date range: {df.FL_DATE.min()} to {df.FL_DATE.max()}\")\n",
    "print(f\"Avg ticket price: ${df.TICKET_PRICE.mean():.2f}\")\n",
    "print(f\"Avg load factor: {df.LOAD_FACTOR.mean():.1%}\")\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "finishTime": 1782933845027,
     "inputWidgets": {},
     "nuid": "210f9200-1eb2-4ce9-8ceb-3f9f680e1027",
     "showTitle": false,
     "startTime": 1782933783205,
     "submitTime": 1782933733514,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Spark DataFrame created\n\uD83D\uDCCA Partitions: 50\n✅ Data cleaned: 500,000 records\n\n\uD83D\uDCCB Sample data:\n+----------+-----+-----------+----------+-------+------+----+-------+--------+------------+--------+---------+--------------+----------+-----------+------------+--------------+--------------+\n|   FL_DATE|MONTH|DAY_OF_WEEK|IS_WEEKEND|AIRLINE|ORIGIN|DEST|  ROUTE|DEP_HOUR|IS_PEAK_HOUR|DISTANCE|DEP_DELAY|SEATS_CAPACITY|SEATS_SOLD|LOAD_FACTOR|TICKET_PRICE|FLIGHT_REVENUE|DELAY_CATEGORY|\n+----------+-----+-----------+----------+-------+------+----+-------+--------+------------+--------+---------+--------------+----------+-----------+------------+--------------+--------------+\n|2023-11-24|   11|          4|         0|     FZ|   MCT| JFK|MCT-JFK|      11|           0|    5625|     -3.0|           180|       117|     0.6544|      742.26|      86844.42|       ON_TIME|\n|2023-01-13|    1|          4|         0|     EK|   JFK| DXB|JFK-DXB|      17|           1|    5219|     92.0|           180|       164|     0.9113|      809.98|     132836.72|   MAJOR_DELAY|\n|2023-02-27|    2|          0|         0|     EY|   DOH| CDG|DOH-CDG|      22|           0|    1810|     40.0|           120|       111|     0.9288|      371.13|      41195.43|MODERATE_DELAY|\n|2023-05-21|    5|          6|         1|     WY|   KWI| DOH|KWI-DOH|       7|           1|    6355|     11.0|           150|       103|     0.6887|      924.58|      95231.74|   MINOR_DELAY|\n|2023-04-25|    4|          1|         0|     G9|   CDG| DXB|CDG-DXB|      15|           0|    6439|     -2.0|           150|       131|     0.8747|      910.76|     119309.56|       ON_TIME|\n+----------+-----+-----------+----------+-------+------+----+-------+--------+------------+--------+---------+--------------+----------+-----------+------------+--------------+--------------+\nonly showing top 5 rows\n\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# ARIA - Cell 2: Convert to Spark DataFrame + Clean\n",
    "# This is where PySpark comes in\n",
    "# ============================================================\n",
    "\n",
    "from pyspark.sql import functions as F\n",
    "\n",
    "# Convert Pandas → Spark DataFrame\n",
    "# In real Azure pipeline: read directly from ADLS Gen2 storage\n",
    "spark_df = spark.createDataFrame(df)\n",
    "\n",
    "print(f\"✅ Spark DataFrame created\")\n",
    "print(f\"\uD83D\uDCCA Partitions: {spark_df.rdd.getNumPartitions()}\")\n",
    "\n",
    "# ---- Data Cleaning ----\n",
    "spark_df = spark_df \\\n",
    "    .filter(F.col(\"DISTANCE\") > 0) \\\n",
    "    .filter(F.col(\"TICKET_PRICE\") > 0) \\\n",
    "    .filter(F.col(\"LOAD_FACTOR\").between(0.1, 1.0)) \\\n",
    "    .dropDuplicates()\n",
    "\n",
    "# ---- Add Delay Category Feature ----\n",
    "spark_df = spark_df.withColumn(\n",
    "    \"DELAY_CATEGORY\",\n",
    "    F.when(F.col(\"DEP_DELAY\") <= 0,   \"ON_TIME\")\n",
    "     .when(F.col(\"DEP_DELAY\") <= 15,  \"MINOR_DELAY\")\n",
    "     .when(F.col(\"DEP_DELAY\") <= 60,  \"MODERATE_DELAY\")\n",
    "     .otherwise(\"MAJOR_DELAY\")\n",
    ")\n",
    "\n",
    "print(f\"✅ Data cleaned: {spark_df.count():,} records\")\n",
    "print(\"\\n\uD83D\uDCCB Sample data:\")\n",
    "spark_df.show(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "finishTime": 1782933936913,
     "inputWidgets": {},
     "nuid": "02e2c4ea-a279-4ba4-a8de-3640d3417359",
     "showTitle": false,
     "startTime": 1782933845093,
     "submitTime": 1782933733518,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Data saved as Delta Lake table: aria_flights\n\uD83C\uDFC6 This is production-grade Azure Databricks storage!\n+------+\n| total|\n+------+\n|500000|\n+------+\n\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# ARIA - Cell 3: Save as Delta Lake Table\n",
    "# Delta = Azure Databricks native format\n",
    "# Supports ACID transactions, time travel, schema enforcement\n",
    "# This is production-grade data storage\n",
    "# ============================================================\n",
    "\n",
    "# Save as Delta table (this is what you mention in interview!)\n",
    "spark_df.write \\\n",
    "    .format(\"delta\") \\\n",
    "    .mode(\"overwrite\") \\\n",
    "    .saveAsTable(\"aria_flights\")\n",
    "\n",
    "print(\"✅ Data saved as Delta Lake table: aria_flights\")\n",
    "print(\"\uD83C\uDFC6 This is production-grade Azure Databricks storage!\")\n",
    "\n",
    "# Verify\n",
    "count = spark.sql(\"SELECT COUNT(*) as total FROM aria_flights\").show()"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "01_Data_Pipeline",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}