{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "finishTime": 1782986865988,
     "inputWidgets": {},
     "nuid": "efb9799a-4174-4845-be36-d6f60d8251f6",
     "showTitle": false,
     "startTime": 1782986789242,
     "submitTime": 1782986767279,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==================================================\nPART 1: Loading data and training models...\n==================================================\n✅ Loaded 500,000 records\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026/07/02 10:07:09 WARNING mlflow.models.model: Model logged without a signature. Signatures will be required for upcoming model registry features as they validate model inputs and denote the expected schema of model outputs. Please visit https://www.mlflow.org/docs/2.13.1/models.html#set-signature-on-logged-model for instructions on setting a model signature on your logged model.\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3a74d495e5d842a8af16b562e902e2c1",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Uploading artifacts:   0%|          | 0/9 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Demand model trained\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026/07/02 10:07:16 WARNING mlflow.models.model: Model logged without a signature. Signatures will be required for upcoming model registry features as they validate model inputs and denote the expected schema of model outputs. Please visit https://www.mlflow.org/docs/2.13.1/models.html#set-signature-on-logged-model for instructions on setting a model signature on your logged model.\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6d1168f4b6a140bda594dd17f3cd12d0",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Uploading artifacts:   0%|          | 0/9 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Pricing model trained\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026/07/02 10:07:24 WARNING mlflow.models.model: Model logged without a signature. Signatures will be required for upcoming model registry features as they validate model inputs and denote the expected schema of model outputs. Please visit https://www.mlflow.org/docs/2.13.1/models.html#set-signature-on-logged-model for instructions on setting a model signature on your logged model.\n"
     ]
    },
    {
     "output_type": "display_data",
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "de9b96b773134ab18bbb486bbf6cc447",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Uploading artifacts:   0%|          | 0/9 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Revenue model trained\n✅ All functions defined!\n\nPART 2: Computing results...\n✅ 7 routes computed\n✅ Total uplift identified: $139,932\n\nPART 3: Writing Streamlit dashboard...\n✅ Dashboard file written!\n\nPART 4: Launching Streamlit...\n⏳ Waiting 15 seconds for Streamlit to start...\n⚠️ Streamlit failed — running displayHTML backup...\nError: /local_disk0/.ephemeral_nfs/envs/pythonEnv-bd0adc71-1500-45ab-a9a5-6736be321274/bin/python: No module named streamlit\n\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# ARIA - 06_Streamlit_Dashboard\n",
    "# COMPLETE SELF-CONTAINED - trains models + launches dashboard\n",
    "# No dependency on any other notebook\n",
    "# ============================================================\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import mlflow\n",
    "import mlflow.xgboost\n",
    "import json\n",
    "import subprocess\n",
    "import time\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.model_selection import train_test_split\n",
    "from xgboost import XGBRegressor\n",
    "\n",
    "# ============================================================\n",
    "# PART 1: Load data + Train models + Define functions\n",
    "# ============================================================\n",
    "print(\"=\"*50)\n",
    "print(\"PART 1: Loading data and training models...\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "df = spark.sql(\"SELECT * FROM aria_flights\").toPandas()\n",
    "le = LabelEncoder()\n",
    "df['AIRLINE_ENC'] = le.fit_transform(df['AIRLINE'])\n",
    "mlflow.set_experiment(\"/ARIA-Experiment\")\n",
    "print(f\"✅ Loaded {len(df):,} records\")\n",
    "\n",
    "def train(X, y, name, **kw):\n",
    "    X_tr,X_te,y_tr,y_te = train_test_split(X,y,test_size=0.2,random_state=42)\n",
    "    with mlflow.start_run(run_name=name):\n",
    "        m = XGBRegressor(**kw,random_state=42,verbosity=0)\n",
    "        m.fit(X_tr,y_tr)\n",
    "        mlflow.xgboost.log_model(m,name)\n",
    "    return m\n",
    "\n",
    "model_demand = train(\n",
    "    df[['MONTH','DAY_OF_WEEK','IS_WEEKEND','DEP_HOUR','IS_PEAK_HOUR',\n",
    "        'DISTANCE','TICKET_PRICE','SEATS_CAPACITY','AIRLINE_ENC']],\n",
    "    df['SEATS_SOLD'],\"demand_model\",\n",
    "    n_estimators=100,max_depth=6,learning_rate=0.1)\n",
    "print(\"✅ Demand model trained\")\n",
    "\n",
    "model_pricing = train(\n",
    "    df[['MONTH','DAY_OF_WEEK','IS_WEEKEND','DEP_HOUR','IS_PEAK_HOUR',\n",
    "        'DISTANCE','LOAD_FACTOR','SEATS_CAPACITY','AIRLINE_ENC']],\n",
    "    df['TICKET_PRICE'],\"pricing_model\",\n",
    "    n_estimators=100,max_depth=6,learning_rate=0.1)\n",
    "print(\"✅ Pricing model trained\")\n",
    "\n",
    "model_revenue = train(\n",
    "    df[['MONTH','DAY_OF_WEEK','IS_WEEKEND','DEP_HOUR','IS_PEAK_HOUR',\n",
    "        'DISTANCE','LOAD_FACTOR','SEATS_CAPACITY','SEATS_SOLD',\n",
    "        'TICKET_PRICE','AIRLINE_ENC']],\n",
    "    df['FLIGHT_REVENUE'],\"revenue_model\",\n",
    "    n_estimators=150,max_depth=7,learning_rate=0.08)\n",
    "print(\"✅ Revenue model trained\")\n",
    "\n",
    "def gf(row,cols):\n",
    "    return pd.DataFrame([row],columns=cols)\n",
    "\n",
    "def forecast_demand(route,month,day_of_week,is_weekend,dep_hour,\n",
    "                    distance,ticket_price,seats_capacity,airline):\n",
    "    enc  = list(le.classes_).index(airline) if airline in le.classes_ else 0\n",
    "    peak = 1 if (7<=dep_hour<=9) or (17<=dep_hour<=19) else 0\n",
    "    f    = gf([month,day_of_week,is_weekend,dep_hour,peak,distance,\n",
    "               ticket_price,seats_capacity,enc],\n",
    "              ['MONTH','DAY_OF_WEEK','IS_WEEKEND','DEP_HOUR','IS_PEAK_HOUR',\n",
    "               'DISTANCE','TICKET_PRICE','SEATS_CAPACITY','AIRLINE_ENC'])\n",
    "    seats = int(model_demand.predict(f)[0])\n",
    "    lf    = round(seats/seats_capacity,3)\n",
    "    return {\"predicted_seats_sold\":seats,\"load_factor\":lf,\n",
    "            \"demand_level\":\"HIGH\" if lf>0.85 else \"MEDIUM\" if lf>0.65 else \"LOW\"}\n",
    "\n",
    "def recommend_price(month,day_of_week,is_weekend,dep_hour,\n",
    "                    distance,load_factor,seats_capacity,airline):\n",
    "    enc  = list(le.classes_).index(airline) if airline in le.classes_ else 0\n",
    "    peak = 1 if (7<=dep_hour<=9) or (17<=dep_hour<=19) else 0\n",
    "    f    = gf([month,day_of_week,is_weekend,dep_hour,peak,distance,\n",
    "               load_factor,seats_capacity,enc],\n",
    "              ['MONTH','DAY_OF_WEEK','IS_WEEKEND','DEP_HOUR','IS_PEAK_HOUR',\n",
    "               'DISTANCE','LOAD_FACTOR','SEATS_CAPACITY','AIRLINE_ENC'])\n",
    "    price = round(float(model_pricing.predict(f)[0]),2)\n",
    "    return {\"recommended_price\":price,\n",
    "            \"pricing_strategy\":\"PREMIUM\" if price>500 else \"STANDARD\" if price>250 else \"BUDGET\"}\n",
    "\n",
    "def optimize_revenue(month,day_of_week,is_weekend,dep_hour,distance,\n",
    "                     load_factor,seats_capacity,seats_sold,ticket_price,airline):\n",
    "    enc  = list(le.classes_).index(airline) if airline in le.classes_ else 0\n",
    "    peak = 1 if (7<=dep_hour<=9) or (17<=dep_hour<=19) else 0\n",
    "    f    = gf([month,day_of_week,is_weekend,dep_hour,peak,distance,\n",
    "               load_factor,seats_capacity,seats_sold,ticket_price,enc],\n",
    "              ['MONTH','DAY_OF_WEEK','IS_WEEKEND','DEP_HOUR','IS_PEAK_HOUR',\n",
    "               'DISTANCE','LOAD_FACTOR','SEATS_CAPACITY','SEATS_SOLD',\n",
    "               'TICKET_PRICE','AIRLINE_ENC'])\n",
    "    rev  = round(float(model_revenue.predict(f)[0]),2)\n",
    "    maxr = seats_capacity*ticket_price\n",
    "    eff  = round(rev/maxr*100,1)\n",
    "    return {\"predicted_revenue\":rev,\"max_possible_revenue\":round(maxr,2),\n",
    "            \"revenue_efficiency\":f\"{eff}%\",\n",
    "            \"recommendation\":\"INCREASE PRICE\" if eff<70 else \"MAINTAIN\" if eff<90 else \"OPTIMAL\"}\n",
    "\n",
    "print(\"✅ All functions defined!\")\n",
    "\n",
    "# ============================================================\n",
    "# PART 2: Compute results + Save JSON\n",
    "# ============================================================\n",
    "print(\"\\nPART 2: Computing results...\")\n",
    "\n",
    "test_flights = [\n",
    "    {\"route\":\"DXB-LHR\",\"month\":12,\"day_of_week\":4,\"is_weekend\":1,\n",
    "     \"dep_hour\":8, \"distance\":3400,\"ticket_price\":450,\"seats_capacity\":350,\"airline\":\"EK\"},\n",
    "    {\"route\":\"DXB-JFK\",\"month\":7, \"day_of_week\":2,\"is_weekend\":0,\n",
    "     \"dep_hour\":14,\"distance\":6800,\"ticket_price\":750,\"seats_capacity\":220,\"airline\":\"EY\"},\n",
    "    {\"route\":\"SHJ-DOH\",\"month\":3, \"day_of_week\":0,\"is_weekend\":0,\n",
    "     \"dep_hour\":6, \"distance\":250, \"ticket_price\":120,\"seats_capacity\":150,\"airline\":\"FZ\"},\n",
    "    {\"route\":\"AUH-CDG\",\"month\":6, \"day_of_week\":5,\"is_weekend\":1,\n",
    "     \"dep_hour\":9, \"distance\":3200,\"ticket_price\":520,\"seats_capacity\":180,\"airline\":\"EY\"},\n",
    "    {\"route\":\"KWI-LHR\",\"month\":12,\"day_of_week\":6,\"is_weekend\":1,\n",
    "     \"dep_hour\":22,\"distance\":2900,\"ticket_price\":380,\"seats_capacity\":220,\"airline\":\"G9\"},\n",
    "    {\"route\":\"DXB-SIN\",\"month\":8, \"day_of_week\":1,\"is_weekend\":0,\n",
    "     \"dep_hour\":23,\"distance\":3650,\"ticket_price\":480,\"seats_capacity\":350,\"airline\":\"EK\"},\n",
    "    {\"route\":\"AUH-LHR\",\"month\":12,\"day_of_week\":3,\"is_weekend\":0,\n",
    "     \"dep_hour\":8, \"distance\":3400,\"ticket_price\":420,\"seats_capacity\":220,\"airline\":\"EY\"},\n",
    "]\n",
    "\n",
    "routes_data = []\n",
    "for f in test_flights:\n",
    "    d = forecast_demand(**f)\n",
    "    p = recommend_price(f[\"month\"],f[\"day_of_week\"],f[\"is_weekend\"],\n",
    "                        f[\"dep_hour\"],f[\"distance\"],d[\"load_factor\"],\n",
    "                        f[\"seats_capacity\"],f[\"airline\"])\n",
    "    r = optimize_revenue(f[\"month\"],f[\"day_of_week\"],f[\"is_weekend\"],\n",
    "                         f[\"dep_hour\"],f[\"distance\"],d[\"load_factor\"],\n",
    "                         f[\"seats_capacity\"],d[\"predicted_seats_sold\"],\n",
    "                         p[\"recommended_price\"],f[\"airline\"])\n",
    "    routes_data.append({\n",
    "        \"route\":f[\"route\"],\"airline\":f[\"airline\"],\n",
    "        \"current_price\":f[\"ticket_price\"],\n",
    "        \"rec_price\":p[\"recommended_price\"],\n",
    "        \"price_uplift\":round(p[\"recommended_price\"]-f[\"ticket_price\"],2),\n",
    "        \"seats_sold\":d[\"predicted_seats_sold\"],\n",
    "        \"capacity\":f[\"seats_capacity\"],\n",
    "        \"load_factor\":round(d[\"load_factor\"]*100,1),\n",
    "        \"demand\":d[\"demand_level\"],\n",
    "        \"strategy\":p[\"pricing_strategy\"],\n",
    "        \"revenue\":r[\"predicted_revenue\"],\n",
    "        \"max_revenue\":r[\"max_possible_revenue\"],\n",
    "        \"efficiency\":r[\"revenue_efficiency\"],\n",
    "        \"action\":r[\"recommendation\"]\n",
    "    })\n",
    "\n",
    "with open(\"/tmp/aria_results.json\",\"w\") as f:\n",
    "    json.dump(routes_data,f)\n",
    "\n",
    "total_current = sum(r[\"seats_sold\"]*r[\"current_price\"] for r in routes_data)\n",
    "total_aria    = sum(r[\"revenue\"] for r in routes_data)\n",
    "total_uplift  = round(total_aria-total_current,2)\n",
    "print(f\"✅ {len(routes_data)} routes computed\")\n",
    "print(f\"✅ Total uplift identified: ${total_uplift:,.0f}\")\n",
    "\n",
    "# ============================================================\n",
    "# PART 3: Write Streamlit dashboard file\n",
    "# ============================================================\n",
    "print(\"\\nPART 3: Writing Streamlit dashboard...\")\n",
    "\n",
    "dashboard = '''\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "import json\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"ARIA - Airline Revenue Intelligence\",\n",
    "    page_icon=\"✈️\", layout=\"wide\"\n",
    ")\n",
    "\n",
    "with open(\"/tmp/aria_results.json\") as f:\n",
    "    routes_data = json.load(f)\n",
    "df = pd.DataFrame(routes_data)\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<h1 style='text-align:center;color:#1E90FF;margin-bottom:4px'>\n",
    "✈️ ARIA — Airline Revenue Intelligence Agent</h1>\n",
    "<p style='text-align:center;color:gray;font-size:13px'>\n",
    "Azure Databricks · LangGraph · MCP Server · XGBoost · MLflow</p>\n",
    "<hr style='margin-bottom:20px'>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "total_current = sum(r[\"seats_sold\"]*r[\"current_price\"] for r in routes_data)\n",
    "total_aria    = sum(r[\"revenue\"] for r in routes_data)\n",
    "total_uplift  = round(total_aria-total_current,2)\n",
    "\n",
    "k1,k2,k3,k4,k5 = st.columns(5)\n",
    "k1.metric(\"✈️ Routes Analyzed\",    len(routes_data))\n",
    "k2.metric(\"\uD83D\uDCE6 Records Processed\",  \"500,000\")\n",
    "k3.metric(\"\uD83C\uDFAF Revenue R²\",         \"0.9999\")\n",
    "k4.metric(\"\uD83D\uDCB0 Revenue Uplift\",     f\"${total_uplift:,.0f}\")\n",
    "k5.metric(\"⚡ Decision Time\",      \"< 3 mins\")\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "tab1,tab2,tab3,tab4 = st.tabs([\n",
    "    \"\uD83D\uDCCA Route Analysis\",\"\uD83D\uDCC8 Charts\",\"\uD83E\uDD16 Agent Trace\",\"\uD83C\uDFC6 Models\"\n",
    "])\n",
    "\n",
    "with tab1:\n",
    "    st.markdown(\"### Multi-Route ARIA Analysis\")\n",
    "    display = df[[\n",
    "        \"route\",\"airline\",\"demand\",\"seats_sold\",\"capacity\",\n",
    "        \"load_factor\",\"current_price\",\"rec_price\",\n",
    "        \"price_uplift\",\"revenue\",\"action\"\n",
    "    ]].rename(columns={\n",
    "        \"route\":\"Route\",\"airline\":\"Airline\",\"demand\":\"Demand\",\n",
    "        \"seats_sold\":\"Seats\",\"capacity\":\"Cap\",\"load_factor\":\"Load%\",\n",
    "        \"current_price\":\"Current $\",\"rec_price\":\"ARIA $\",\n",
    "        \"price_uplift\":\"Uplift $\",\"revenue\":\"Revenue $\",\"action\":\"Action\"\n",
    "    })\n",
    "    st.dataframe(display, use_container_width=True, height=310)\n",
    "    ca,cb,cc = st.columns(3)\n",
    "    ca.error(f\"**Current Revenue**\\\\n\\\\n${total_current:,.0f}\")\n",
    "    cb.success(f\"**ARIA Revenue**\\\\n\\\\n${total_aria:,.0f}\")\n",
    "    cc.info(f\"**Uplift Opportunity**\\\\n\\\\n+${total_uplift:,.0f}\")\n",
    "\n",
    "with tab2:\n",
    "    c1,c2 = st.columns(2)\n",
    "    with c1:\n",
    "        st.markdown(\"#### Revenue: Current vs ARIA\")\n",
    "        fig = go.Figure()\n",
    "        fig.add_bar(name=\"Current\",\n",
    "            x=df[\"route\"],\n",
    "            y=[r[\"seats_sold\"]*r[\"current_price\"] for r in routes_data],\n",
    "            marker_color=\"#ff4444\")\n",
    "        fig.add_bar(name=\"ARIA\",\n",
    "            x=df[\"route\"],y=df[\"revenue\"],\n",
    "            marker_color=\"#00cc44\")\n",
    "        fig.update_layout(barmode=\"group\",height=350,\n",
    "            paper_bgcolor=\"rgba(0,0,0,0)\",\n",
    "            plot_bgcolor=\"rgba(0,0,0,0)\")\n",
    "        st.plotly_chart(fig,use_container_width=True)\n",
    "    with c2:\n",
    "        st.markdown(\"#### Load Factor by Route\")\n",
    "        colors = [\"#00cc44\" if r[\"load_factor\"]>85\n",
    "                  else \"#ffaa00\" if r[\"load_factor\"]>65\n",
    "                  else \"#ff4444\" for r in routes_data]\n",
    "        fig2 = go.Figure(go.Bar(\n",
    "            x=df[\"route\"],y=df[\"load_factor\"],\n",
    "            marker_color=colors,\n",
    "            text=[f\"{r['load_factor']}%\" for r in routes_data],\n",
    "            textposition=\"auto\"))\n",
    "        fig2.add_hline(y=85,line_dash=\"dash\",\n",
    "            line_color=\"white\",annotation_text=\"Target 85%\")\n",
    "        fig2.update_layout(height=350,\n",
    "            paper_bgcolor=\"rgba(0,0,0,0)\",\n",
    "            plot_bgcolor=\"rgba(0,0,0,0)\")\n",
    "        st.plotly_chart(fig2,use_container_width=True)\n",
    "\n",
    "    st.markdown(\"#### Price Uplift per Route\")\n",
    "    fig3 = px.bar(df,x=\"route\",y=\"price_uplift\",color=\"strategy\",\n",
    "        color_discrete_map={\"PREMIUM\":\"#1E90FF\",\"STANDARD\":\"#ffaa00\",\"BUDGET\":\"#00cc44\"},\n",
    "        text=\"price_uplift\",labels={\"price_uplift\":\"Uplift ($)\"})\n",
    "    fig3.update_traces(texttemplate=\"+$%{text}\",textposition=\"outside\")\n",
    "    fig3.update_layout(height=300,\n",
    "        paper_bgcolor=\"rgba(0,0,0,0)\",\n",
    "        plot_bgcolor=\"rgba(0,0,0,0)\")\n",
    "    st.plotly_chart(fig3,use_container_width=True)\n",
    "\n",
    "with tab3:\n",
    "    st.markdown(\"### \uD83E\uDD16 LangGraph Agent Execution Trace\")\n",
    "    st.info(\"Each flight runs through 4 LangGraph nodes via MCP server\")\n",
    "    sel = st.selectbox(\"Select route:\",\n",
    "        [f\"{r['route']} ({r['airline']})\" for r in routes_data])\n",
    "    idx = [f\"{r['route']} ({r['airline']})\" for r in routes_data].index(sel)\n",
    "    rd  = routes_data[idx]\n",
    "    c1,c2 = st.columns([1,2])\n",
    "    with c1:\n",
    "        st.write(f\"Route: **{rd['route']}**\")\n",
    "        st.write(f\"Airline: **{rd['airline']}**\")\n",
    "        st.write(f\"Current Price: **${rd['current_price']}**\")\n",
    "        st.write(f\"Capacity: **{rd['capacity']} seats**\")\n",
    "    with c2:\n",
    "        st.markdown(f\"\"\"\n",
    "| Step | Agent | Output |\n",
    "|------|-------|--------|\n",
    "| 1 | \uD83D\uDD35 Demand Agent | {rd['seats_sold']} seats · {rd['load_factor']}% load · {rd['demand']} |\n",
    "| 2 | \uD83D\uDFE1 Pricing Agent | ${rd['rec_price']} · {rd['strategy']} |\n",
    "| 3 | \uD83D\uDFE2 Revenue Agent | ${rd['revenue']:,.0f} · {rd['efficiency']} |\n",
    "| 4 | \uD83D\uDCCB Report Agent  | **{rd['action']}** · +${rd['price_uplift']}/ticket |\n",
    "        \"\"\")\n",
    "    st.markdown(\"**MCP Audit Log**\")\n",
    "    st.dataframe(pd.DataFrame([\n",
    "        {\"Tool\":\"forecast_demand\", \"Status\":\"✅\",\"Result\":f\"{rd['seats_sold']} seats, {rd['load_factor']}%\"},\n",
    "        {\"Tool\":\"recommend_price\", \"Status\":\"✅\",\"Result\":f\"${rd['rec_price']} ({rd['strategy']})\"},\n",
    "        {\"Tool\":\"optimize_revenue\",\"Status\":\"✅\",\"Result\":f\"${rd['revenue']:,.0f} ({rd['efficiency']})\"},\n",
    "    ]),use_container_width=True)\n",
    "\n",
    "with tab4:\n",
    "    st.markdown(\"### \uD83C\uDFC6 Model Performance\")\n",
    "    m1,m2,m3 = st.columns(3)\n",
    "    m1.metric(\"Demand R²\",  \"0.8843\",\"XGBoost\")\n",
    "    m2.metric(\"Pricing R²\", \"0.9969\",\"XGBoost\")\n",
    "    m3.metric(\"Revenue R²\", \"0.9999\",\"XGBoost\")\n",
    "    st.dataframe(pd.DataFrame({\n",
    "        \"Model\":[\"Demand\",\"Pricing\",\"Revenue\"],\n",
    "        \"R²\":[0.8843,0.9969,0.9999],\n",
    "        \"Accuracy\":[\"88.4%\",\"99.7%\",\"99.99%\"],\n",
    "        \"Tracked\":[\"MLflow\",\"MLflow\",\"MLflow\"]\n",
    "    }),use_container_width=True)\n",
    "    st.markdown(\"### ⚙️ Tech Stack\")\n",
    "    t1,t2,t3,t4 = st.columns(4)\n",
    "    t1.success(\"**Data**\\\\n\\\\nDatabricks\\\\nPySpark\\\\nDelta Lake\")\n",
    "    t2.info(\"**ML**\\\\n\\\\nXGBoost\\\\nMLflow\\\\nModel Registry\")\n",
    "    t3.warning(\"**Agents**\\\\n\\\\nLangGraph\\\\nMCP Server\\\\nOpenAI\")\n",
    "    t4.success(\"**UI**\\\\n\\\\nStreamlit\\\\nPlotly\\\\nDatabricks\")\n",
    "'''\n",
    "\n",
    "with open(\"/tmp/aria_dashboard.py\",\"w\") as f:\n",
    "    f.write(dashboard)\n",
    "print(\"✅ Dashboard file written!\")\n",
    "\n",
    "# ============================================================\n",
    "# PART 4: Launch Streamlit\n",
    "# ============================================================\n",
    "print(\"\\nPART 4: Launching Streamlit...\")\n",
    "\n",
    "subprocess.run([\"pkill\",\"-f\",\"streamlit\"],capture_output=True)\n",
    "time.sleep(3)\n",
    "\n",
    "process = subprocess.Popen(\n",
    "    [\"python\",\"-m\",\"streamlit\",\"run\",\"/tmp/aria_dashboard.py\",\n",
    "     \"--server.port\",\"8501\",\n",
    "     \"--server.headless\",\"true\",\n",
    "     \"--server.enableCORS\",\"false\",\n",
    "     \"--server.enableXsrfProtection\",\"false\",\n",
    "     \"--browser.gatherUsageStats\",\"false\"],\n",
    "    stdout=subprocess.PIPE,\n",
    "    stderr=subprocess.PIPE\n",
    ")\n",
    "\n",
    "print(\"⏳ Waiting 15 seconds for Streamlit to start...\")\n",
    "time.sleep(15)\n",
    "\n",
    "check = subprocess.run([\"pgrep\",\"-f\",\"streamlit\"],\n",
    "                       capture_output=True,text=True)\n",
    "\n",
    "if check.stdout.strip():\n",
    "    print(\"✅ Streamlit is RUNNING!\")\n",
    "    ctx        = dbutils.notebook.entry_point.getDbutils().notebook().getContext()\n",
    "    host       = ctx.browserHostName().get()\n",
    "    cluster_id = spark.conf.get(\"spark.databricks.clusterUsageTags.clusterId\")\n",
    "    org_id     = ctx.workspaceId().get()\n",
    "    url        = f\"https://{host}/driver-proxy/o/{org_id}/{cluster_id}/8501/\"\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"\uD83C\uDF89 OPEN YOUR DASHBOARD:\")\n",
    "    print(f\"   {url}\")\n",
    "    print(\"=\"*60)\n",
    "else:\n",
    "    print(\"⚠️ Streamlit failed — running displayHTML backup...\")\n",
    "    out, err = process.communicate(timeout=5)\n",
    "    print(\"Error:\", err.decode()[:200])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "finishTime": 1782987263053,
     "inputWidgets": {},
     "nuid": "17bbb73c-d61d-48b2-9e36-d4713b0fcf6c",
     "showTitle": false,
     "startTime": 1782987228187,
     "submitTime": 1782987227948,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Installing Streamlit...\n✅ Streamlit installed!\nStreamlit version: Streamlit, version 1.58.0\n⏳ Waiting 20 seconds...\n✅ Streamlit RUNNING!\n\n============================================================\n\uD83C\uDF89 OPEN YOUR DASHBOARD:\n   https://adb-7405607151403283.3.azuredatabricks.net/driver-proxy/o/7405607151403283/0626-122804-6nz13cte/8501/\n============================================================\n"
     ]
    }
   ],
   "source": [
    "import subprocess\n",
    "import time\n",
    "\n",
    "# Step 1: Install streamlit properly\n",
    "print(\"Installing Streamlit...\")\n",
    "result = subprocess.run(\n",
    "    [\"pip\", \"install\", \"streamlit\", \"plotly\", \"--quiet\"],\n",
    "    capture_output=True, text=True\n",
    ")\n",
    "print(\"✅ Streamlit installed!\")\n",
    "\n",
    "# Step 2: Verify installation\n",
    "verify = subprocess.run(\n",
    "    [\"python\", \"-m\", \"streamlit\", \"--version\"],\n",
    "    capture_output=True, text=True\n",
    ")\n",
    "print(f\"Streamlit version: {verify.stdout.strip()}\")\n",
    "\n",
    "# Step 3: Kill any existing process\n",
    "subprocess.run([\"pkill\", \"-f\", \"streamlit\"], capture_output=True)\n",
    "time.sleep(2)\n",
    "\n",
    "# Step 4: Launch\n",
    "process = subprocess.Popen(\n",
    "    [\"python\", \"-m\", \"streamlit\", \"run\", \"/tmp/aria_dashboard.py\",\n",
    "     \"--server.port\", \"8501\",\n",
    "     \"--server.headless\", \"true\",\n",
    "     \"--server.enableCORS\", \"false\",\n",
    "     \"--server.enableXsrfProtection\", \"false\",\n",
    "     \"--browser.gatherUsageStats\", \"false\"],\n",
    "    stdout=subprocess.PIPE,\n",
    "    stderr=subprocess.PIPE\n",
    ")\n",
    "\n",
    "print(\"⏳ Waiting 20 seconds...\")\n",
    "time.sleep(20)\n",
    "\n",
    "# Step 5: Check\n",
    "check = subprocess.run([\"pgrep\", \"-f\", \"streamlit\"],\n",
    "                       capture_output=True, text=True)\n",
    "\n",
    "if check.stdout.strip():\n",
    "    print(\"✅ Streamlit RUNNING!\")\n",
    "    ctx        = dbutils.notebook.entry_point.getDbutils().notebook().getContext()\n",
    "    host       = ctx.browserHostName().get()\n",
    "    cluster_id = spark.conf.get(\"spark.databricks.clusterUsageTags.clusterId\")\n",
    "    org_id     = ctx.workspaceId().get()\n",
    "    url        = f\"https://{host}/driver-proxy/o/{org_id}/{cluster_id}/8501/\"\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"\uD83C\uDF89 OPEN YOUR DASHBOARD:\")\n",
    "    print(f\"   {url}\")\n",
    "    print(\"=\"*60)\n",
    "else:\n",
    "    print(\"❌ Still failing — reading error:\")\n",
    "    out, err = process.communicate(timeout=5)\n",
    "    print(err.decode()[:500])"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "experimentId": "450047789329140",
    "pythonIndentUnit": 4
   },
   "notebookName": "06_Streamlit_Dashboard",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}